"""`lai gen`: turn the registry into the files the stack runs on.

Everything here is a pure function of (registry, host lookups): no writes, no
network. `artifacts()` is the whole output of `lai gen`; cli.py only writes it.

    gen/llama-swap.yaml    one entry per enabled model + the co-residency matrix
    gen/llama-env.sh       environment wrapper every llama-server starts through
    gen/vllm-<id>.sh       container launcher per engine="vllm" model
    gen/opencode.json      client config, installed to Settings.opencode_config

Because the proxy config and the client config come from the same registry, a
model's routing key cannot drift between them. That drift has no error message:
llama-server ignores the request's `model` field and answers anyway, so the
symptom is fluent output from the wrong model.
"""

from __future__ import annotations

import json
import re
import shlex
from dataclasses import dataclass
from pathlib import Path

from lai import yamlout
from lai.host import Host
from lai.paths import REPO_ROOT, TEMPLATES_DIR, vllm_launcher
from lai.registry import Registry
from lai.schema import Model, Settings

BANNER = "GENERATED by `lai gen` from models.py. Do not edit: changes are overwritten."
SWAP_SCHEMA = "https://raw.githubusercontent.com/mostlygeek/llama-swap/refs/heads/main/config-schema.json"
OPENCODE_PROVIDER = "llamacpp"  # opencode model refs are "llamacpp/<id>"; renaming breaks saved sessions


@dataclass(frozen=True)
class Artifact:
    path: Path
    content: str
    executable: bool = False


def artifacts(registry: Registry, host: Host, gen_dir: Path) -> list[Artifact]:
    """Every file `lai gen` writes, in write order."""
    settings = registry.settings
    files = [
        Artifact(gen_dir / "llama-swap.yaml", llama_swap_config(registry, host, gen_dir)),
        Artifact(gen_dir / "llama-env.sh", env_wrapper(settings), executable=True),
    ]
    files += [
        Artifact(vllm_launcher(gen_dir, m.id), vllm_launcher_script(m, settings), executable=True)
        for m in registry.active()
        if m.engine == "vllm"
    ]
    opencode = json.dumps(opencode_config(registry), indent=2, ensure_ascii=False) + "\n"
    files.append(Artifact(gen_dir / "opencode.json", opencode))
    return files


# ===========================================================================
# llama-server command line
# ===========================================================================


def llama_server_args(model: Model, settings: Settings, weights: str, mmproj: str | None) -> list[list[str]]:
    """llama-server arguments as groups of tokens: one group per line of the YAML
    `cmd` block, flattened for `lai run`. `${PORT}` is llama-swap's macro."""
    groups = [
        ["--port", "${PORT}"],
        ["--host", settings.listen_host],
        ["-a", model.id],
        ["-m", weights],
    ]
    if mmproj:
        groups.append(["--mmproj", mmproj])
    if model.device:
        groups.append(["--device", model.device])
    groups.append(["-ngl", str(model.gpu_layers)])
    groups.append(["-sm", model.split_mode])
    if model.cpu_moe_layers:
        groups.append(["--n-cpu-moe", str(model.cpu_moe_layers)])
    if model.load_mode:
        groups.append(["--load-mode", model.load_mode])
    groups.append(["-c", str(model.context)])
    groups.append(["-ub", str(model.ubatch), "-b", str(model.batch)])
    groups.append(["--parallel", str(model.parallel)])
    groups.append(["-fa", model.flash_attn])
    if model.kv_type:
        groups.append(["-ctk", model.kv_type, "-ctv", model.kv_type])
    groups.append(["--jinja"])  # without it tool calls come back as prose
    groups += [[f"--{key.replace('_', '-')}", str(value)] for key, value in model.sampler.items()]
    groups += group_flags(model.extra_args)
    return groups


def group_flags(tokens: list[str]) -> list[list[str]]:
    """Group a flat argv into [flag, values...] so each flag reads on its own line."""
    groups: list[list[str]] = []
    for token in tokens:
        starts_flag = token.startswith("-") and not re.fullmatch(r"-\d+(\.\d+)?", token)
        if starts_flag or not groups:
            groups.append([token])
        else:
            groups[-1].append(token)
    return groups


_SHELL_SAFE = re.compile(r"[A-Za-z0-9_@%+=:,./-]+|\$\{[A-Z_]+\}")


def shell_join(tokens: list[str]) -> str:
    """Join tokens for a llama-swap `cmd` line, which is split like a shell would.
    Quotes only when needed, and leaves llama-swap macros such as ${PORT} bare."""
    return " ".join(t if _SHELL_SAFE.fullmatch(t) else shlex.quote(t) for t in tokens)


# ===========================================================================
# llama-swap
# ===========================================================================


def llama_swap_config(registry: Registry, host: Host, gen_dir: Path) -> str:
    settings = registry.settings
    document = {
        "healthCheckTimeout": settings.health_timeout_s,
        "startPort": settings.backend_start_port,
        "globalTTL": settings.idle_ttl_s,
        "logLevel": "info",
        "logToStdout": "both",
        "sendLoadingState": True,
        "includeAliasesInList": False,
        "store": {"path": str(settings.activity_db)},
        "models": {m.id: swap_model_entry(m, settings, host, gen_dir) for m in registry.active()},
        "routing": {"router": coresidency_router(registry)},
    }
    header = "\n".join([
        BANNER,
        f"yaml-language-server: $schema={SWAP_SCHEMA}",
        "",
        "Co-residency: models pinned to different cards may be loaded together (one",
        "per card). Models pinned to no card appear in no matrix set, which llama-swap",
        "treats as run-alone: loading one evicts everything else.",
    ])
    return yamlout.dump(document, header=header)


def swap_model_entry(model: Model, settings: Settings, host: Host, gen_dir: Path) -> dict:
    entry: dict = {"name": model.name}
    if model.notes:
        entry["description"] = model.notes
    entry["cmd"] = backend_command(model, settings, host, gen_dir)
    entry["ttl"] = model.ttl if model.ttl is not None else -1  # -1: use globalTTL
    entry["capabilities"] = {
        "tools": model.tools,
        "context": model.slot_context,
        "in": ["text", "image"] if model.vision else ["text"],
        "out": ["text"],
    }
    if model.request_params:
        entry["setParams"] = model.request_params
    return entry


def backend_command(model: Model, settings: Settings, host: Host, gen_dir: Path) -> str:
    """The `cmd` block: wrapper + llama-server args, or the vLLM launcher."""
    if model.engine == "vllm":
        return f"{vllm_launcher(gen_dir, model.id)} ${{PORT}}"
    weights = host.find(model.weights) or f"MISSING:{settings.model_dir / model.weights}"
    mmproj = host.find(model.mmproj) if model.mmproj else None
    lines = [str(gen_dir / "llama-env.sh")]
    lines += [shell_join(group) for group in llama_server_args(model, settings, weights, mmproj)]
    return "\n".join(lines) + "\n"


def coresidency_router(registry: Registry) -> dict:
    """llama-swap's matrix router: at most one pinned model per card at a time.

    Each card's models become an OR group, groups are ANDed, and llama-swap
    treats any subset of a set as valid. Unpinned models are in no set, so
    they run alone. With fewer than two populated cards nothing can co-reside
    and the default group router applies.
    """
    groups = [
        registry.pinned_to(card) for card in registry.settings.cards if registry.pinned_to(card)
    ]
    if len(groups) < 2:
        return {"use": "group"}
    variables: dict[str, str] = {}
    evict_costs: dict[str, int] = {}
    expressions = []
    for letter, models in zip("abcdefghijklmnopqrstuvwxyz", groups, strict=False):
        names = []
        for index, model in enumerate(models):
            name = f"{letter}{index}"  # matrix vars must be 1-8 alphanumerics
            variables[name] = model.id
            evict_costs[name] = max(1, int(model.vram_gb))  # bigger reloads cost more
            names.append(name)
        expressions.append(f"({' | '.join(names)})")
    return {
        "use": "matrix",
        "settings": {
            "matrix": {
                "vars": variables,
                "evict_costs": evict_costs,
                "sets": {"coresident": " & ".join(expressions)},
            }
        },
    }


# ===========================================================================
# Shell scripts and the systemd unit
# ===========================================================================


def fill_template(name: str, **values: str) -> str:
    """Substitute @KEY@ placeholders in a template; fail loudly on leftovers."""
    text = (TEMPLATES_DIR / name).read_text()
    body = values.pop("BODY", None)
    for key, value in {"BANNER": BANNER, **values}.items():
        text = text.replace(f"@{key}@", value)
    leftover = sorted(set(re.findall(r"@[A-Z_]+@", text)) - ({"@BODY@"} if body is not None else set()))
    if leftover:
        raise ValueError(f"template {name}: unfilled placeholders {leftover}")
    return text.replace("@BODY@", body) if body is not None else text


def env_wrapper(settings: Settings) -> str:
    return fill_template(
        "llama-env.sh",
        ONEAPI_SETVARS=shlex.quote(str(settings.oneapi_setvars)),
        LLAMA_SERVER=shlex.quote(str(settings.llama_server)),
    )


def vllm_launcher_script(model: Model, settings: Settings, repo_root: Path = REPO_ROOT) -> str:
    return fill_template(
        "vllm-launcher.sh",
        MODEL_ID=shlex.quote(model.id),
        MODEL_DIR=shlex.quote(str(settings.model_dir)),
        CONTEXT=str(model.context),
        REPO_ROOT=shlex.quote(str(repo_root)),
        BODY=(model.launcher or "").strip("\n"),  # the template supplies the final newline
    )


def systemd_unit(settings: Settings, swap_binary: str, swap_config: Path) -> str:
    listen = f"{settings.listen_host}:{settings.listen_port}"
    exec_start = f"{swap_binary} --config {swap_config} --listen {listen}"
    return fill_template("llama-swap.service", EXEC_START=exec_start, HOME=str(Path.home()))


# ===========================================================================
# opencode
# ===========================================================================


def opencode_config(registry: Registry) -> dict:
    settings = registry.settings
    config = {
        "$schema": "https://opencode.ai/config.json",
        "model": f"{OPENCODE_PROVIDER}/{settings.default_model}",
        "small_model": f"{OPENCODE_PROVIDER}/{settings.small_model}",
        "share": "disabled",
        "provider": {
            OPENCODE_PROVIDER: {
                "npm": "@ai-sdk/openai-compatible",
                "name": "llama-swap (local)",
                # baseURL must be inside `options`: at the provider root it is ignored
                # and requests go to undefined/chat/completions.
                "options": {"baseURL": f"{settings.base_url}/v1", "apiKey": "dummy"},
                "models": {m.id: opencode_model_entry(m) for m in registry.active()},
            }
        },
    }
    return deep_merge(config, settings.opencode_extra)


def opencode_model_entry(model: Model) -> dict:
    entry: dict = {
        "name": model.name,
        # opencode compacts based on limit.context, so it must be what one request
        # actually gets from the server, not the total -c.
        "limit": {"context": model.slot_context, "output": model.max_output},
    }
    if model.reasoning_field:
        # Without this, a turn that only reasons renders as a blank response.
        entry["reasoning"] = True
        entry["interleaved"] = {"field": model.reasoning_field}
    if model.vision:
        # opencode silently strips image parts for custom openai-compatible models
        # unless `modalities` says otherwise (undocumented); `attachment` alone is
        # not enough, so both are set.
        entry["attachment"] = True
        entry["modalities"] = {"input": ["text", "image"], "output": ["text"]}
    return entry


def deep_merge(base: dict, override: dict) -> dict:
    """A copy of `base` with `override` merged in: nested dicts merge, anything else replaces."""
    merged = dict(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged
